#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR
echo -e "\033[34;1mInstalling $(basename $SCRIPT_DIR)...\033[0m"

ORIGINAL_ARGS=("$@")

# Argument flags
ARG_NONE_I3=0
ARG_NO_SUDO=0
ARG_ANDROID=0

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --none-i3)
            ARG_NONE_I3=1
            shift
            ;;
        -a|--android)
            ARG_ANDROID=1
            shift
            ;;
        --no-sudo)
            ARG_NO_SUDO=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

function isProtected () {
    [[ ! -f "$SCRIPT_DIR/../.protected" ]] && return 1
    mapfile -t < $SCRIPT_DIR/../.protected
    protectedFiles="${MAPFILE[@]}"
    for ProtectedFile in $protectedFiles; do
        [[ "$ProtectedFile" == "$*" ]] && return 0
    done
    return 1
}
function isNoneI3() {
    if [[ $ARG_NONE_I3 == 1 ]]; then
        local file="$1"
        local config="$SCRIPT_DIR/install_config"
        [[ ! -f "$config" ]] && return 1
        source "$config"
        for uniq in "${i3[@]}"; do
            [[ "$file" == "$uniq" ]] && return 0
        done
        return 1
    fi
    return 1
}
function isAndroid() {
    if [[ $ARG_ANDROID == 1 ]]; then
        return 0
    fi
    return 1
}
function hasNoSudo() {
    if [[ $ARG_NO_SUDO == 1 ]]; then
        return 0
    fi
    return 1
}

# Install /home files
if [ -d $SCRIPT_DIR/home ]; then 
    echo -e "\033[1mLinking up home\033[0m"
    cd $SCRIPT_DIR/home
    for FILE in $(rg --files --hidden); do
        isProtected "$HOME/$FILE" && echo -e " \033[31m$FILE is protected\033[0m" && continue
        isNoneI3 "$FILE" && echo -e " \033[33m$FILE is i3 specific, skipping\033[0m" && continue

        # handle SSH files
        [[ $(dirname "$HOME/$FILE") == "$HOME/.ssh" ]] &&
            echo -e " \033[2mCopying $FILE\033[0m" &&
            cp -f "$SCRIPT_DIR/home/$FILE" "$HOME/$FILE" &&
            continue
        
        echo -e " \033[2mCreating softlink for $FILE\033[0m"
        [ ! -d $(dirname "$HOME/$FILE") ] && mkdir -p $(dirname "$HOME/$FILE")
        ln -sf "$SCRIPT_DIR/home/$FILE" "$HOME/$FILE"
    done
fi

# Install /bin files
if [ -d $SCRIPT_DIR/bin ]; then 
    echo -e "\033[1mInstall bin scripts\033[0m"
    cd $SCRIPT_DIR/bin
    isAndroid && echo -e " \033[2mAndroid detected, installing to termux bin folder\033[0m"
    for FILE in $(rg --files --hidden); do
        isProtected "/usr/bin/$FILE" && echo -e " \033[31m$FILE is protected\033[0m" && continue
        isNoneI3 "$FILE" && echo -e " \033[33m$FILE is i3 specific, skipping\033[0m" && continue
        
        if isAndroid; then
            echo -e " \033[2mCopying $FILE\033[0m"
            cp -f $FILE /data/data/com.termux/files/usr/bin/$FILE
            continue
        fi

        echo -e " \033[2mCopying $FILE\033[0m"
        sudo cp -f $FILE /usr/bin/$FILE
    done
fi

# Install /etc files (Manual)
if [ -d $SCRIPT_DIR/etc ]; then
    echo -e "\033[1mInstall etc configs\033[0m"

    # Adjust this list as needed
    filesToMove=(etc/modprobe.d/nobeep.conf
                 etc/pacman.conf
                 etc/X11/xorg.conf.d/00-keyboard.conf)

    cd $SCRIPT_DIR
    for FILE in "${filesToMove[@]}"; do
        filename=$(basename "$FILE")
        isProtected "usr/$FILE" && echo -e " \033[31m$FILE is protected\033[0m" && continue
        isNoneI3 "$FILE" && echo -e " \033[33m$FILE is i3 specific, skipping\033[0m" && continue
        isAndroid && echo -e " \033[33m$FILE is not for Android, skipping\033[0m" && continue
        
        echo -e " \033[2mCopying $filename\033[0m"
        sudo cp -f "$SCRIPT_DIR/$FILE" "/$FILE"
    done
fi

#echo -e "\033[1mSetting up terminal aliases\033[0m"
#cd /usr/bin/
#for TERM in term gnome-terminal default-terminal TerminalEmulator; do
#    echo -e " \033[2mCreating softlink for $TERM => terminal\033[0m"
#    sudo ln -sf terminal $TERM
#done


# Install /usr files
if [ -d $SCRIPT_DIR/usr ]; then
    echo -e "\033[1mSetting usr files\033[0m"
    cd $SCRIPT_DIR/usr
    for FILE in $(rg --files --hidden); do
        isProtected "$FILE" && echo -e " \033[31m$FILE is protected\033[0m" && continue
        isNoneI3 "$FILE" && echo -e " \033[33m$FILE is i3 specific, skipping\033[0m" && continue
        isAndroid && echo -e " \033[33m$FILE is not for Android, skipping\033[0m" && continue

        echo -e " \033[2mCopying $FILE\033[0m"
        [ ! -d $(dirname "/usr/$FILE") ] && sudo mkdir -p $(dirname "/usr/$FILE")
        sudo cp -rf $FILE "/usr/$FILE"
    done
fi

# Get tools folder if non exist
if [ ! -d $SCRIPT_DIR/../Tools ]; then
    cd $SCRIPT_DIR/..
    git clone git@github.com:AndreasBrostrom/Tools.git
fi
if [ -d $SCRIPT_DIR/../Tools ]; then
    echo -e "\033[1mFetching scripts from Tools\033[0m"
    $SCRIPT_DIR/../Tools/installScripts "${ORIGINAL_ARGS[@]}" --link
fi


# Get ssh folder if non exist
if [ ! -d $SCRIPT_DIR/../secure ]; then
    cd $SCRIPT_DIR/..
    git clone git@github.com:AndreasBrostrom/secure.git
fi
if [ -d $SCRIPT_DIR/../secure/ssh ]; then
    echo -e "\033[1mHome secret from secure\033[0m"
    cd $SCRIPT_DIR/../secure/ssh
    [ ! -d "$HOME/.ssh" ] && mkdir -p $HOME/.ssh
    EXISTING=($(ls $HOME/.ssh))
    for FILE in $(rg --files --hidden); do
        echo -e " \033[2mCopying $FILE\033[0m"
        cp -f $FILE $HOME/.ssh/$FILE
    done
fi

# SSH permissions
echo -e " \033[2mFixing SSH permissions\033[0m"
chmod 700 $HOME/.ssh
chmod 600 $HOME/.ssh/config
chmod 600 $HOME/.ssh/authorized_keys
chmod 600 $HOME/.ssh/*id_rsa
chmod 644 $HOME/.ssh/*.pub