# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s expand_aliases

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000000
HISTFILESIZE=20000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set object colors for ls
eval "$(dircolors ~/.config/dir_colors)"

# Source all conf.d files in order
if [ -d ~/.config/bash/conf.d ]; then
  for f in ~/.config/bash/conf.d/*.sh; do
    [ -f "$f" ] && . "$f"
  done
fi

# Completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Custom completions
if [ -d ~/.config/bash/completions ]; then
  for f in ~/.config/bash/completions/*.bash; do
    [ -f "$f" ] && . "$f"
  done
fi

if [ -z "$SSH_AGENT_PID" ]; then
  eval `ssh-agent -s` >/dev/null 2>/dev/null
fi

eval "$(starship init bash)"
