#!/bin/bash
# .config/i3status/config
#   read_file todo {
#       path = "/home/andre/.cache/i3status_monitor/todo"
#       format = "Todo: %content"
#       format_bad = ""
#       color_good = "#586E75"
#   }


_file="todo"
_path="$HOME/.cache/i3status_monitor"

while true; do 
    sleep 10

    [ ! -d "$_path" ] && mkdir -p $_path

    todos=$(wc -l ~/todo | xargs -n 1 2>&1 | head -n 1)

    if [[ $todos -gt 0 ]]; then
        echo "$todos todos detected"
        echo "$todos" > $_path/$_file
    else
        echo "No todos detected"
        echo "" > $_path/$_file
    fi
done
