#!/bin/bash

ACF_DIR="$HOME/.steam/steam/steamapps"
output=()

# Find all .acf files and process them
while IFS= read -r file; do
    appid=$(grep -m1 '"appid"' "$file" | sed -E 's/.*"appid"[[:space:]]*"([0-9]+)".*/\1/')
    name=$(grep -m1 '"name"' "$file" | sed -E 's/.*"name"[[:space:]]*"([^"]+)".*/\1/')
    output+=("AppID: $(printf %-12s "$appid") Name: $name")
done < <(find "$ACF_DIR" -type f -name 'appmanifest_*.acf')

# Sort and print
printf "%s\n" "${output[@]}" | sort -k3

